version: '3.9'

services:
  db:
    image: postgres:14
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: USERNAME_FROM_SECRETS/diplomabackend:latest
    container_name: web
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: diplomanginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:
  static_volume:
  media_volume:
