name: Deploy Django Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy project files to server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/app

      - name: Create .env file on server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          cat > /app/.env << EOL
          SECRET_KEY=${{ secrets.ENV_SECRET_KEY }}
          DEBUG=${{ secrets.ENV_DEBUG }}
          ALLOWED_HOSTS=${{ secrets.ENV_ALLOWED_HOSTS }}
          
          POSTGRES_DB=${{ secrets.ENV_POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.ENV_POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.ENV_POSTGRES_PASSWORD }}
          POSTGRES_HOST=${{ secrets.ENV_POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.ENV_POSTGRES_PORT }}
          
          DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}
          DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          EOL
          EOF

      - name: Build and run containers with Docker Compose
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          cd /app
          docker-compose down --volumes --remove-orphans
          docker-compose up --build -d
          EOF
