name: Run Postman Collections

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Create folder for reports
        run: mkdir -p newman

      - name: Run all Postman collections
        run: |
          for collection in ./postman/*.postman_collection.json; do
            name=$(basename "$collection" .postman_collection.json | tr ' ' '_' | tr -d '[:punct:]')
            echo "Running $name"
            newman run "$collection" \
              --environment ./postman/Localhost.postman_environment.json \
              --reporters cli,html \
              --reporter-html-export "newman/${name}_report.html"
          done

      - name: Upload Newman reports
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-reports
          path: newman/

